# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 3407

# The following parameters are used to define the model and the data
data_folder: ./data
output_folder: !ref ./results/<seed>
save_folder: !ref <output_folder>/save
plda_folder: !ref <output_folder>/plda
train_log: !ref <output_folder>/train_log.txt
test_only: True  # If True, only test the model
enable_plda: True  # If True, use PLDA to score the embeddings

# Path where data manifest files will be stored
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
test_annotation: !ref <data_folder>/test.json
split_ratio: [80, 20, 0]
skip_prep: False

# Path where processed data will be stored
processed_train: !ref <data_folder>/processed/train
processed_valid: !ref <data_folder>/processed/valid
processed_test: !ref <data_folder>/processed/test

# PCA parameters
pca_components: 140  # 0.99

# Training Parameters
sample_rate: 16000
number_of_epochs: 5000
save_interval: 500
batch_size: 16
lr_start: 1e-3
lr_final: 1e-6
n_classes: 28 # In this case, we have 28 speakers
emb_dim: 512 # dimensionality of the embeddings
num_workers: 8
